name: paginated_items_builder
description: Easier to display items in a list/grid view from your controllers directly or handling state internally with support for pagination.
version: 1.0.0
homepage: https://github.com/rithik-dev/paginated_items_builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  visibility_detector: ^0.2.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
